-- MySQL Script generated by MySQL Workbench
-- Wed Oct 24 02:44:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ventas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ventas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ventas` DEFAULT CHARACTER SET utf8 ;
USE `ventas` ;

-- -----------------------------------------------------
-- Table `ventas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`usuarios` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido_paterno` VARCHAR(30) NOT NULL,
  `apellido_materno` VARCHAR(30) NOT NULL,
  `usuario` VARCHAR(20) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `perfil` VARCHAR(20) NULL DEFAULT NULL,
  `estado` INT(10) UNSIGNED NULL DEFAULT NULL,
  `ultimo_login` DATETIME NULL DEFAULT NULL,
  `fecha` TIMESTAMP(6) NULL DEFAULT NULL,
  `vigencia` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
