-- MySQL Script generated by MySQL Workbench
-- Tue Nov  6 15:34:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ventas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ventas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ventas` DEFAULT CHARACTER SET utf8 ;
USE `ventas` ;

-- -----------------------------------------------------
-- Table `ventas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`usuarios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido_paterno` VARCHAR(30) NOT NULL,
  `apellido_materno` VARCHAR(30) NOT NULL,
  `usuario` VARCHAR(20) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `perfil` VARCHAR(20) NULL,
  `estado` INT UNSIGNED NULL,
  `ultimo_login` DATETIME NULL,
  `fecha` TIMESTAMP(6) NULL,
  `vigencia` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas`.`tarifas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`tarifas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_tarifa` VARCHAR(20) NOT NULL,
  `rango_inicial` INT UNSIGNED NOT NULL,
  `rango_final` INT UNSIGNED NOT NULL,
  `giro` INT UNSIGNED NOT NULL,
  `importe_tarifa` DECIMAL(8,2) UNSIGNED NOT NULL,
  `partida_contable` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas`.`rutas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`rutas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_ruta` VARCHAR(10) NOT NULL,
  `ciudad` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas`.`oficinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`oficinas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_oficina` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas`.`lecturistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`lecturistas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido_paterno` VARCHAR(30) NOT NULL,
  `apellido_materno` VARCHAR(30) NULL,
  `rutas_id` INT UNSIGNED NOT NULL,
  `oficinas_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `rutas_id`, `oficinas_id`),
  INDEX `fk_lecturistas_rutas_idx` (`rutas_id` ASC),
  INDEX `fk_lecturistas_oficinas1_idx` (`oficinas_id` ASC),
  CONSTRAINT `fk_lecturistas_rutas`
    FOREIGN KEY (`rutas_id`)
    REFERENCES `ventas`.`rutas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lecturistas_oficinas1`
    FOREIGN KEY (`oficinas_id`)
    REFERENCES `ventas`.`oficinas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas`.`descripciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`descripciones` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion_corta` VARCHAR(45) NOT NULL,
  `descripcion_larga` VARCHAR(45) NOT NULL,
  `fecha_ingreso` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
